"USE STRICT"; //THAT CONVERT ALL JS CODE TO A NEWER VERION

alert(3+3); // WE ARE NOT USEING BROWSER 

console.log(3+
    3);
// CODE READABILITY SHUDLE BE HIGH
console.log("WHAT IS JS");
// tc39.eS iS STANDRERDIZATION FOR JS


let NAME = "YASH MAHAJAN";
let AGE = 20;
let IALOGIN = true;


// NUMBER = 2 TO POWER 53
// BIGINT IS USE FOR BIG INTIGER NO
//STRING IS FOR THE CHARACTER ""
//BOOLEN IS TRUE OR FALSE
//NULL IS STAND ALONE VALUE
//UNDEFINED IS ACCURED WHE WE NOT GIVE AN ANY VALUE
//SYMBOL UNIQUE
//OBJECT

console.log(typeof undefined); // UNDEFINED
console.log(typeof NULL);// OBJECT

